"start":
  "0":
    - "-1"
    - "3.5"
    - "-1.5707963267948966"
  "1":
    - "1"
    - "3.5"
    - "-1.5707963267948966"
  "2":
    - "1"
    - "-3.5"
    - "1.5707963267948966"
  "3":
    - "-1"
    - "-3.5"
    - "1.5707963267948966"
